name: Deploy KeyHack

on:
  push:
    branches:
      - main

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        run: |
          cd /var/www/html
          git fetch origin main
          git reset --hard origin/main
          
      - name: Install Python dependencies
        run: |
          cd /var/www/html
          /var/www/html/backend/venv/bin/pip install -r backend/requirements.txt
          
      - name: Restart FastAPI
        run: |
          sudo systemctl restart fastapi.service
